export const LOGIN_ACTION = {
    LOGIN_START: "LOGIN_START",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGIN_CLEAR: "LOGIN_CLEAR"
  };
  
  export const STATUS = {
    ERROR: "ERROR",
    SUCCESS: "SUCCESS",
    LOADING: "LOADING",
    CLEAR: "CLEAR"
  };

  export const REG_ACTION = {
    REG_START: "REG_START",
    REG_SUCCESS: "REG_SUCCESS",
    REG_FAILURE: "REG_FAILURE",
    REG_CLEAR: "REG_CLEAR"
  };